{% set name = "galois" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/galois-{{ version }}.tar.gz
  sha256: bffdd595a29eefe7234075e508e685e328297b56b0279efa1d83dce2a68d92a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=62
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - numpy >=1.21.0,<2.2
    - numba >=0.55,<0.61
    - typing_extensions >=4.0.0

test:
  imports:
    - galois
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A performant NumPy extension for Galois fields and their applications
  dev_url: https://github.com/mhostetter/galois
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - myzhang1029
