{% set name = "stripe" %}
{% set version = "11.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stripe-{{ version }}.tar.gz
  sha256: bc3e0358ffc23d5ecfa8aafec1fa4f048ee8107c3237bcb00003e68c8c96fa02

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - wheel
    - pip
  run:
    - python
    - typing_extensions <=4.2.0,>3.7.2  # [py<37]
    - typing_extensions >=4.5.0  # [py>=37]
    - requests >=2.20  # [py>=30]

test:
  imports:
    - stripe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stripe/stripe-python
  summary: Python bindings for the Stripe API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - myzhang1029
